dist: bionic
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-dev python3-pip
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv update
jobs:
  include:
    stage: test
    name: "Linting"
    script: pylint */*.py
    script: pytest
