dist: bionic
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python3-dev python3-pip
language: python
python:
  - "3.7"
install:
  - pip install pipenv
  - pipenv update
script:
  - "pytest src/tests/test.py"
