version: "3"

volumes:
  postgres_data:

services:
  db:
    image: "postgres:12"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gymregiment.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 80:80
      - 443:443
