"""empty message

Revision ID: 03fa89926914
Revises: 6938299bd280
Create Date: 2020-01-25 22:46:18.706705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy_utils import ChoiceType
from src.account import Sex


# revision identifiers, used by Alembic.
revision = '03fa89926914'
down_revision = '6938299bd280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biometrics', sa.Column('sex', ChoiceType(Sex, impl=sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biometrics', 'sex')
    # ### end Alembic commands ###
