"""empty message

Revision ID: 6938299bd280
Revises: fa53fdf0ed35
Create Date: 2020-01-25 16:57:21.740795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6938299bd280'
down_revision = 'fa53fdf0ed35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('biometric_id', sa.Integer(), nullable=True))
    op.add_column('accounts', sa.Column('dob', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'accounts', 'biometrics', ['biometric_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'dob')
    op.drop_column('accounts', 'biometric_id')
    op.drop_table('biometrics')
    # ### end Alembic commands ###
